# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jinsoo Cha Coaching
email: jinsoocha222@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A software engineer by day and a coach by night, specializing in personal finance and cultural transition.
baseurl: "" # the subpath of your site, e.g. /blog
url: "jinsoocha.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
