# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jinsoo Cha 
email: jinsoocha222@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A full stack developer in San Francisco.
baseurl: "" # the subpath of your site, e.g. /blog
url: "jinsoocha.github.io" # the base hostname & protocol for your site
github_username:  jinsoocha
linkedin_username: jinsoocha

# Build settings
markdown: kramdown
